FROM ubuntu:14.04

# env vars
ENV HOME /root
ENV GOPATH /go
ENV PATH /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# GOPATH
RUN mkdir -p /go

RUN apt-get update
RUN apt-get install -y build-essential mercurial git subversion wget curl

# go 1.10 tarball
RUN wget -qO- http://golang.org/dl/go1.10.1.linux-amd64.tar.gz | tar -C /usr/local -xzf -

ENV GOPATH /go

RUN go get github.com/ahmetb/govvv

COPY . /go/src/github.com/go-loom/loom
WORKDIR /go/src/github.com/go-loom/loom

RUN govvv install -pkg github.com/go-loom/loom/pkg/version github.com/go-loom/loom/cmd/loom/...

ENTRYPOINT ["loom"]
CMD ["-h"]
