// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	SubscribeJobRequest
	SubscribeJobResponse
	ReportJobRequest
	ReportJobResponse
	ReportJobDoneRequest
	ReportJobDoneResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubscribeJobResponse_Status int32

const (
	SubscribeJobResponse_NoJob  SubscribeJobResponse_Status = 0
	SubscribeJobResponse_NewJob SubscribeJobResponse_Status = 1
)

var SubscribeJobResponse_Status_name = map[int32]string{
	0: "NoJob",
	1: "NewJob",
}
var SubscribeJobResponse_Status_value = map[string]int32{
	"NoJob":  0,
	"NewJob": 1,
}

func (x SubscribeJobResponse_Status) String() string {
	return proto.EnumName(SubscribeJobResponse_Status_name, int32(x))
}
func (SubscribeJobResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type SubscribeJobRequest struct {
	WorkerId  string `protobuf:"bytes,1,opt,name=worker_id,json=workerId" json:"worker_id,omitempty"`
	TopicName string `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
}

func (m *SubscribeJobRequest) Reset()                    { *m = SubscribeJobRequest{} }
func (m *SubscribeJobRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeJobRequest) ProtoMessage()               {}
func (*SubscribeJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubscribeJobRequest) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *SubscribeJobRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type SubscribeJobResponse struct {
	JobId     []byte                      `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobMsg    []byte                      `protobuf:"bytes,2,opt,name=job_msg,json=jobMsg,proto3" json:"job_msg,omitempty"`
	JobStatus SubscribeJobResponse_Status `protobuf:"varint,3,opt,name=job_status,json=jobStatus,enum=loom.server.SubscribeJobResponse_Status" json:"job_status,omitempty"`
}

func (m *SubscribeJobResponse) Reset()                    { *m = SubscribeJobResponse{} }
func (m *SubscribeJobResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeJobResponse) ProtoMessage()               {}
func (*SubscribeJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeJobResponse) GetJobId() []byte {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *SubscribeJobResponse) GetJobMsg() []byte {
	if m != nil {
		return m.JobMsg
	}
	return nil
}

func (m *SubscribeJobResponse) GetJobStatus() SubscribeJobResponse_Status {
	if m != nil {
		return m.JobStatus
	}
	return SubscribeJobResponse_NoJob
}

type ReportJobRequest struct {
	JobId     []byte `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId  string `protobuf:"bytes,2,opt,name=worker_id,json=workerId" json:"worker_id,omitempty"`
	TopicName string `protobuf:"bytes,3,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	JobMsg    []byte `protobuf:"bytes,4,opt,name=job_msg,json=jobMsg,proto3" json:"job_msg,omitempty"`
}

func (m *ReportJobRequest) Reset()                    { *m = ReportJobRequest{} }
func (m *ReportJobRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportJobRequest) ProtoMessage()               {}
func (*ReportJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReportJobRequest) GetJobId() []byte {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *ReportJobRequest) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *ReportJobRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ReportJobRequest) GetJobMsg() []byte {
	if m != nil {
		return m.JobMsg
	}
	return nil
}

type ReportJobResponse struct {
}

func (m *ReportJobResponse) Reset()                    { *m = ReportJobResponse{} }
func (m *ReportJobResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportJobResponse) ProtoMessage()               {}
func (*ReportJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReportJobDoneRequest struct {
	JobId     []byte `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId  string `protobuf:"bytes,2,opt,name=worker_id,json=workerId" json:"worker_id,omitempty"`
	TopicName string `protobuf:"bytes,3,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
}

func (m *ReportJobDoneRequest) Reset()                    { *m = ReportJobDoneRequest{} }
func (m *ReportJobDoneRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportJobDoneRequest) ProtoMessage()               {}
func (*ReportJobDoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReportJobDoneRequest) GetJobId() []byte {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *ReportJobDoneRequest) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

func (m *ReportJobDoneRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type ReportJobDoneResponse struct {
}

func (m *ReportJobDoneResponse) Reset()                    { *m = ReportJobDoneResponse{} }
func (m *ReportJobDoneResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportJobDoneResponse) ProtoMessage()               {}
func (*ReportJobDoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*SubscribeJobRequest)(nil), "loom.server.SubscribeJobRequest")
	proto.RegisterType((*SubscribeJobResponse)(nil), "loom.server.SubscribeJobResponse")
	proto.RegisterType((*ReportJobRequest)(nil), "loom.server.ReportJobRequest")
	proto.RegisterType((*ReportJobResponse)(nil), "loom.server.ReportJobResponse")
	proto.RegisterType((*ReportJobDoneRequest)(nil), "loom.server.ReportJobDoneRequest")
	proto.RegisterType((*ReportJobDoneResponse)(nil), "loom.server.ReportJobDoneResponse")
	proto.RegisterEnum("loom.server.SubscribeJobResponse_Status", SubscribeJobResponse_Status_name, SubscribeJobResponse_Status_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4d, 0x4f, 0xea, 0x50,
	0x10, 0x7d, 0xe5, 0xa3, 0xef, 0x75, 0x1e, 0x18, 0x1c, 0x20, 0x10, 0x0c, 0x0a, 0x77, 0xc5, 0xaa,
	0x0b, 0xfc, 0x07, 0xc6, 0xc4, 0x40, 0x94, 0xc4, 0x92, 0xb8, 0x70, 0x43, 0xb8, 0x30, 0x21, 0x45,
	0xcb, 0xd4, 0x7b, 0x8b, 0xec, 0xfc, 0x4d, 0xfe, 0x43, 0x4d, 0x5b, 0x25, 0xb7, 0x04, 0x70, 0xe5,
	0x6e, 0x72, 0x66, 0xee, 0x99, 0x73, 0xce, 0xe4, 0x42, 0x59, 0x93, 0x7a, 0xf5, 0x67, 0xe4, 0x86,
	0x8a, 0x23, 0xc6, 0xff, 0xcf, 0xcc, 0x81, 0x1b, 0x63, 0xa4, 0xc4, 0x3d, 0x54, 0xc7, 0x6b, 0xa9,
	0x67, 0xca, 0x97, 0x34, 0x64, 0xe9, 0xd1, 0xcb, 0x9a, 0x74, 0x84, 0x67, 0xe0, 0x6c, 0x58, 0x3d,
	0x91, 0x9a, 0xf8, 0xf3, 0xa6, 0xd5, 0xb1, 0x7a, 0x8e, 0xf7, 0x2f, 0x05, 0x06, 0x73, 0x6c, 0x03,
	0x44, 0x1c, 0xfa, 0xb3, 0xc9, 0x6a, 0x1a, 0x50, 0x33, 0x97, 0x74, 0x9d, 0x04, 0x19, 0x4d, 0x03,
	0x12, 0xef, 0x16, 0xd4, 0xb2, 0x9c, 0x3a, 0xe4, 0x95, 0x26, 0xac, 0x83, 0xbd, 0x64, 0xf9, 0xcd,
	0x58, 0xf2, 0x8a, 0x4b, 0x96, 0x83, 0x39, 0x36, 0xe0, 0x6f, 0x0c, 0x07, 0x7a, 0x91, 0x70, 0x95,
	0xbc, 0x78, 0xea, 0x4e, 0x2f, 0xf0, 0x06, 0x20, 0x6e, 0xe8, 0x68, 0x1a, 0xad, 0x75, 0x33, 0xdf,
	0xb1, 0x7a, 0x27, 0xfd, 0x9e, 0x6b, 0xa8, 0x77, 0xf7, 0xad, 0x71, 0xc7, 0xc9, 0xbc, 0xe7, 0x2c,
	0x59, 0xa6, 0xa5, 0xb8, 0x00, 0x3b, 0xad, 0xd0, 0x81, 0xe2, 0x88, 0x87, 0x2c, 0x2b, 0x7f, 0x10,
	0xc0, 0x1e, 0xd1, 0x26, 0xae, 0x2d, 0xf1, 0x06, 0x15, 0x8f, 0x42, 0x56, 0x91, 0x11, 0xc1, 0x01,
	0xb5, 0x99, 0x64, 0x72, 0x47, 0x93, 0xc9, 0xef, 0x24, 0x63, 0x3a, 0x2d, 0x98, 0x4e, 0x45, 0x15,
	0x4e, 0x8d, 0xfd, 0xa9, 0x0f, 0xe1, 0x43, 0x6d, 0x0b, 0x5e, 0xf3, 0x8a, 0x7e, 0x4f, 0x98, 0x68,
	0x40, 0x7d, 0x67, 0x55, 0xaa, 0xa1, 0xff, 0x61, 0x41, 0xe1, 0x96, 0x39, 0xc0, 0x31, 0x94, 0xcc,
	0xb0, 0xb1, 0x73, 0xe4, 0x0e, 0x89, 0xcc, 0x56, 0xf7, 0xc7, 0x4b, 0xe1, 0x10, 0x9c, 0xed, 0x5a,
	0x6c, 0x67, 0xe6, 0x77, 0xcf, 0xd1, 0x3a, 0x3f, 0xd4, 0xfe, 0xe2, 0x7a, 0x80, 0x72, 0xc6, 0x02,
	0x76, 0xf7, 0x3f, 0x30, 0x92, 0x6c, 0x89, 0x63, 0x23, 0x29, 0xef, 0x55, 0xe1, 0x31, 0x17, 0x4a,
	0x69, 0x27, 0x5f, 0xe7, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x90, 0x1e, 0xba, 0xe6, 0x4b, 0x03,
	0x00, 0x00,
}
